_format_version: "3.0"
services:
  - name: sgd-api
    url: http://api:8000
    routes:
      - name: sgd-api-route
        paths:
          - /
        strip_path: false
      - name: health-route
        paths:
          - /healthz
          - /metrics
        strip_path: false
        plugins:
          - name: request-transformer
            config:
              remove:
                headers:
                  - Authorization
plugins:
  - name: request-transformer
    route: sgd-api-route
    config:
      add:
        headers: ["X-Budget-Org: demo-user"]
  - name: jwt
    route: sgd-api-route
    config:
      key_claim_name: iss
      claims_to_verify: [exp]
      run_on_preflight: false
  - name: rate-limiting
    route: sgd-api-route
    config:
      second: 10
      minute: 100
      policy: local
      limit_by: consumer
      fault_tolerant: true
  - name: request-size-limiting
    route: sgd-api-route
    config:
      allowed_payload_size: 50
      size_unit: megabytes
  - name: cors
    route: sgd-api-route
    config:
      origins: ["*"]
      methods: [GET, POST, PUT, DELETE, OPTIONS]
      headers: [Authorization, Content-Type, X-Requested-With]
      credentials: false
      max_age: 3600
consumers:
  - username: demo
    custom_id: demo-user
  - username: service
    custom_id: service-account
jwt_secrets:
  - consumer: demo
    key: demo-issuer
    secret: demo-secret-key-for-testing-only
    algorithm: HS256
  - consumer: service
    key: service-issuer
    secret: service-secret-key-for-internal-use
    algorithm: HS256
# For Clerk integration, configure CLERK_JWKS_URL in environment
# Kong will validate JWTs using the JWKS endpoint
