---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: nanodesigner
type: Opaque
data:
  # Base64 encoded values - CHANGE THESE IN PRODUCTION
  OPENROUTER_API_KEY: eW91ci1vcGVucm91dGVyLWtleQ==  # your-openrouter-key
  GEMINI_API_KEY: eW91ci1nZW1pbmkta2V5  # your-gemini-key
  LANGFUSE_PUBLIC_KEY: eW91ci1sYW5nZnVzZS1wdWJsaWMta2V5  # your-langfuse-public-key
  LANGFUSE_SECRET_KEY: eW91ci1sYW5nZnVzZS1zZWNyZXQta2V5  # your-langfuse-secret-key

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: nanodesigner
data:
  DATABASE_URL: "postgresql://postgres:password@postgres:5432/nanodesigner"
  REDIS_URL: "redis://redis:6379"
  QDRANT_URL: "http://qdrant:6333"
  LANGFUSE_HOST: "https://cloud.langfuse.com"
  PYTECTOR_MODE: "strict"
  STORAGE_TYPE: "local"
  LOG_LEVEL: "INFO"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: nanodesigner
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: nanodesigner/api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: REDIS_URL
        - name: QDRANT_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: QDRANT_URL
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: OPENROUTER_API_KEY
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: GEMINI_API_KEY
        - name: LANGFUSE_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: LANGFUSE_PUBLIC_KEY
        - name: LANGFUSE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: LANGFUSE_SECRET_KEY
        - name: LANGFUSE_HOST
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: LANGFUSE_HOST
        - name: PYTECTOR_MODE
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: PYTECTOR_MODE
        - name: STORAGE_TYPE
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: STORAGE_TYPE
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: storage
          mountPath: /app/var/storage
      volumes:
      - name: storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: nanodesigner
  labels:
    app: api
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: api

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: nanodesigner
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
